grafana:
  admin:
    existingSecret: grafana       # The name of the secret you've already created
    adminPasswordKey: admin.password  # The key within the secret where the password is stored (case-sensitive)

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

  dashboardsConfigMaps:
    - grafana-dashboards