apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: LoadBalancer # Change from NodePort to LoadBalancer
  ports:
    - port: 80 # Service port to expose
      targetPort: 80 # Port on the NGINX container
  selector:
    app: nginx
