apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read/write
  resources:
    requests:
      storage: 1Gi  # Specify the amount of storage you need
