apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/yair232/status-page.git'
  destinations:
    - namespace: '*'
      server: '*'
  description: Default project for ArgoCD
