apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
  labels:
    app: fluentbit
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-binding
roleRef:
  kind: ClusterRole
  name: fluentbit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentbit-sa
    namespace: elastic-stack

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-sa
  namespace: elastic-stack
  labels:
    app: fluentbit