apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yair232/status-page.git'
    targetRevision: HEAD  # Use a specific branch or tag if needed
    path: 'k8s/ingress/helm-nginx'  # Adjust according to your repo structure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
