apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yair232/status-page.git'
    targetRevision: HEAD
    path: 'k8s/ingress/helm-nginx'  # Adjust to your repo structure
    helm:
      valueFiles:
        - 'values.yaml'  # Make sure this file exists in the helm-nginx directory
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress  # Ensure this matches your intended namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
