apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/elasticsearch
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      jsonPointers:
        - "/metadata/managedFields"
        - "/metadata/resourceVersion"
        - "/status"
