apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-app
  namespace: argocd
spec:
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/logging
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "ServerSideApply=true"
    # Ignoring specific annotation differences to avoid unnecessary OutOfSync statuses
    ignoreDifferences:
      - kind: StatefulSet
        jsonPointers:
          - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
  syncWave: "7"
