apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-app
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/monitor
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - "ServerSideApply=true"
    automated:
      prune: true
      selfHeal: true
  syncWave: "1"
  hooks:
    - type: PostSync
      command: ["sh", "-c", "echo 'Waiting 250 seconds before proceeding...'; sleep 250"]
