apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: app-manager
  name: my-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-apps
    repoURL: https://github.com/yair232/status-page.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Define each application here
  sources:
    - source:
        repoURL: https://github.com/yair232/status-page.git
        path: k8s/namespace
        targetRevision: HEAD
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      syncWave: '0'
      
    - source:
        repoURL: https://github.com/yair232/status-page.git
        path: k8s/monitor
        targetRevision: HEAD
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      syncWave: '1'
      
    - source:
        repoURL: https://github.com/yair232/status-page.git
        path: k8s/monitor/kube-prometheus-stack
        targetRevision: HEAD
        helm:
          valueFiles:
            - prom-values.yaml
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      syncWave: '2'
      
    - source:
        repoURL: https://github.com/yair232/status-page.git
        path: k8s/app
        targetRevision: HEAD
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      syncWave: '3'
      
    - source:
        repoURL: https://github.com/yair232/status-page.git
        path: k8s/monitor/prometheus-nginx-exporter
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-nginx.yaml
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      syncWave: '4'
      
    - source:
        repoURL: https://github.com/yair232/status-page.git
        path: k8s/monitor/prometheus-redis-exporter
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-redis.yaml
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      syncWave: '5'
