apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-exporter
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/monitor/prometheus-nginx-exporter
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-nginx.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncWave: '6'
  hooks:
   - type: PostSync
     command: ["sh", "-c", "echo 'Waiting 250 seconds before proceeding...'; sleep 10"]
