alertmanager:
  enabled: true
  alertmanagerSpec:
    config:
      global:
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'y.rproject123@gmail.com'
        smtp_auth_username: 'y.rproject123@gmail.com'
        smtp_auth_password: 'RY123456789'  # Consider using a Kubernetes Secret for this
        smtp_require_tls: true
      route:
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
        receiver: 'email-notifications'
      receivers:
        - name: 'email-notifications'
          email_configs:
            - to: 'yair.ginat@nitzanim.tech'
              from: 'y.rproject123@gmail.com'
              subject: 'Alert: {{ .AlertName }}'
              send_resolved: true
            - to: 'ron.tzidky@nitzanim.tech'
              from: 'y.rproject123@gmail.com'
              subject: 'Alert: {{ .AlertName }}'
              send_resolved: true
