apiVersion: monitoring.coreos.com/v1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-email-config
  namespace: monitoring
spec:
  receivers:
    - name: email-notifications
      emailConfigs:
        - to: 'yair.ginat@nitzanim.tech'
          from: 'y.rproject123@gmail.com'
          smarthost: 'smtp.gmail.com:587'
          authUsername: 'y.rproject123@gmail.com'
          authPassword:
            name: smtp-auth
            key: smtp_auth_password 
          requireTLS: true
          subject: 'Alert: {{ .CommonAnnotations.summary }}'
          sendResolved: true
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: email-notifications
