apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ron.tzidky@nitzanim.tech
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
