apiVersion: v1
kind: Service
metadata:
  name: grafana-svc-bridge
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  type: ExternalName
  externalName: prometheus-app-grafana.monitoring.svc.cluster.local
