apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-app
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/monitor
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - "ServerSideApply=true"
      - "ForceConflicts=true"
    automated:
      prune: true
      selfHeal: true
  syncWave: "2"
  hooks:
    - type: PreSync
      command: ["sh", "-c", "echo 'Waiting for Django and app.yaml readiness...'; until kubectl get pods -n default -l app=django -o jsonpath='{.items[0].status.containerStatuses[0].ready}' | grep true && kubectl get pods -n default -l app=app -o jsonpath='{.items[0].status.containerStatuses[0].ready}' | grep true; do sleep 5; done"]
    - type: PostSync
      command: ["sh", "-c", "echo 'Waiting 250 seconds before proceeding...'; sleep 250"]
